# Team Token : HyB0pGFwgZuQrw.atlasv1.zEkcvUrnMBX89oypD9ByccZTuHEjf9kCC1jOvPsDyizyI5zlee6Xnbb8UkzGsWuHdPc

# Workspace ID는 Workspace > Settings > General 화면에서 조회 가능 (예 : ws-ARsviW6JRkpHS4pV)


# List Variables : `instance_type`볍수의 ID 값 조회
# https://www.terraform.io/docs/cloud/api/workspace-variables.html#list-variables
# GET /workspaces/:workspace_id/vars
curl \
  --header "Authorization: Bearer HyB0pGFwgZuQrw.atlasv1.zEkcvUrnMBX89oypD9ByccZTuHEjf9kCC1jOvPsDyizyI5zlee6Xnbb8UkzGsWuHdPc" \
  --header "Content-Type: application/vnd.api+json" \
  "https://app.terraform.io/api/v2/workspaces/ws-ARsviW6JRkpHS4pV/vars"

# Update Variables for instance type
# 위 명령어로 조회된 instance_type 변수의 ID값을 REQUEST_URL에 적용
# https://www.terraform.io/docs/cloud/api/workspace-variables.html#update-variables
# PATCH /workspaces/:workspace_id/vars/:variable_id
curl \
  --header "Authorization: Bearer HyB0pGFwgZuQrw.atlasv1.zEkcvUrnMBX89oypD9ByccZTuHEjf9kCC1jOvPsDyizyI5zlee6Xnbb8UkzGsWuHdPc" \
  --header "Content-Type: application/vnd.api+json" \
  --request PATCH \
  --data @update_instance_type.json \
  https://app.terraform.io/api/v2/workspaces/ws-ARsviW6JRkpHS4pV/vars/var-rhrnyu4AX2YfTWFG


# Create Run
curl \
  --header "Authorization: Bearer HyB0pGFwgZuQrw.atlasv1.zEkcvUrnMBX89oypD9ByccZTuHEjf9kCC1jOvPsDyizyI5zlee6Xnbb8UkzGsWuHdPc" \
  --header "Content-Type: application/vnd.api+json" \
  --request POST \
  --data @create_run_payload.json \
  https://app.terraform.io/api/v2/runs


# Get Run Details : Create Run 수행 결과로 Return 되는 값에서 RUN_ID 확인
curl \
  --header "Authorization: Bearer HyB0pGFwgZuQrw.atlasv1.zEkcvUrnMBX89oypD9ByccZTuHEjf9kCC1jOvPsDyizyI5zlee6Xnbb8UkzGsWuHdPc" \
  https://app.terraform.io/api/v2/runs/run-WDa6JWUcsv5yQykt


  #Fetch the Current state Version for a workspace
curl \
  --header "Authorization: Bearer HyB0pGFwgZuQrw.atlasv1.zEkcvUrnMBX89oypD9ByccZTuHEjf9kCC1jOvPsDyizyI5zlee6Xnbb8UkzGsWuHdPc" \
  --header "Content-Type: application/vnd.api+json" \
  https://app.terraform.io/api/v2/workspaces/ws-ARsviW6JRkpHS4pV/current-state-version


# Show state version
curl \
  --header "Authorization: Bearer KGwo5OVk3Uxjmg.atlasv1.sztgzwwcjrZiUcays6meBJYb5EBu03UOkTnEezMSn9rzVfkecstDcqmcg3Du3rPlILY" \
  --header "Content-Type: application/vnd.api+json" \
  https://app.terraform.io/api/v2/state-versions/sv-yNE7TSRWQes9cMqa
# 세부정보는 hosted-state-download-url 상의 file을 다운로드하거나 읽어드려서 정보 확인